apps/clients/urls.py
from django.conf.urls import url
from django.views.decorators.gzip import gzip_page

from apps.clients.views import PostJobView,  ClientProfileView, FindJobView, FindDetailsView, ClientDetailList,\
    JobDetailView, FreelancerActiveView, MyJobView, MyJobDetails, FetchJobDetailsView,InviteValidation, ChatView
from apps.freelancer.general import check_group_required


urlpatterns = [
    url(r'^jobpost/', gzip_page(PostJobView.as_view()), name='post-job'),
    url(r'^jobs/', gzip_page(FindJobView.as_view()), name='find_job'),
    url(r'^my-jobs/', gzip_page(MyJobView.as_view()), name='my_jobs'),
    url(r'^my-jobsDetails/(?P<slug>[\w-]+)', gzip_page(check_group_required(MyJobDetails.as_view())), name='my_jobsDetails'),
    url(r'^client-detail/', gzip_page(check_group_required(ClientDetailList.as_view())),name='client-detail'),
    url(r'^job-list-detail/(?P<slug>[\w-]+)', gzip_page(FindDetailsView.as_view()),name='find_job_details'),
    url(r'^client-profile/$', ClientProfileView.as_view(), name='client_profile'),
    url(r'^job-details/(?P<slug>[\w-]+)', gzip_page(JobDetailView.as_view()), name='job_details'),
    url(r'^client-freelancer/', FreelancerActiveView.as_view(), name='freelancer_active'),
    url(r'^fetch_job_details/', gzip_page(FetchJobDetailsView.as_view()), name='fetch_job_details'),
    url(r'^is_invited/', InviteValidation.as_view(), name='is_invited'),
    url(r'^message/', ChatView.as_view(), name='chat_view'),


    ]

apps/freelancer/urls.py
from django.conf.urls import url
from django.views.decorators.gzip import gzip_page

from apps.freelancer.general import check_group_required
from .views import AddFreelancerView, AddEmploymentHistoryView, AddEducationDetailView, AddCertificationView, \
    AddHourlyRateView, EditFreelancerProfileView, AddPortfolioForm, AddCompany, EditOverview, EditEducationDetails, \
    EditEmploymentHistory, EditPortfolio, EditCertificationView, EditProfileView, EditProfilePicView, \
    EditProfileSkillsView, FindFreelancers, WorkCategory, FreelancerDetailView, CountrySelectView, RegionSelectView, \
    ClientActiveView, AddAvailability, AddSkillView

urlpatterns = [
    url(r'^company/add/$', gzip_page(AddCompany.as_view()), name='add_company'),
    # starting of freelancer profile
    url(r'^create-profile/$', gzip_page(check_group_required(AddFreelancerView.as_view())), name='add_freelancer_profile'),
    url(r'^employmentHistory/$', AddEmploymentHistoryView.as_view(), name='add_employmentHistory'),
    url(r'^educationDetails/$', AddEducationDetailView.as_view(), name='add_educationDetails'),
    url(r'^certification/$', gzip_page(AddCertificationView.as_view()), name='add_certification'),
    url(r'^create-rate/$', AddHourlyRateView.as_view(), name='add_rate'),
    url(r'^freelancer-profile/$', gzip_page(EditFreelancerProfileView.as_view()), name='freelancer_profile'),
    url(r'^portfolio/$', AddPortfolioForm.as_view(), name='add_portfolio'),
    url(r'^edit-overview/$', EditOverview.as_view(), name='edit_overview'),
    url(r'^edit-education-details/$', EditEducationDetails.as_view(), name='edit_education_details'),
    url(r'^edit-employment/$', EditEmploymentHistory.as_view(), name='edit_employment'),
    url(r'^edit-portfolio/$', EditPortfolio.as_view(), name='edit_portfolio'),
    url(r'^edit-certificate/$', EditCertificationView.as_view(), name='edit_certificate'),
    url(r'^edit/$', EditProfileView.as_view(), name='edit_profile'),
    url(r'^edit-picture/$', EditProfilePicView.as_view(), name='edit_picture'),
    url(r'^edit-skills/$', EditProfileSkillsView.as_view(), name='edit_skills'),
    url(r'^freelancers-list/$', gzip_page(FindFreelancers.as_view()), name='find_freelancer'),
    url(r'^working-category/$', gzip_page(WorkCategory.as_view()), name='working_category'),
    url(r'^freelancer-detail/(?P<slug>[\w-]+)/$', FreelancerDetailView.as_view(), name='freelancer_detail'),
    url(r'^country/$', gzip_page(CountrySelectView.as_view()), name='country_select'),
    url(r'^region/$', RegionSelectView.as_view(), name='region_select'),
    url(r'^availability/$', AddAvailability.as_view(), name='add_availability'),
    url(r'^skill/$', gzip_page(AddSkillView.as_view()), name='skill_add'),
    # end of freelancer profile

    url(r'^freelancer-as-client/', gzip_page(ClientActiveView.as_view()), name='client_active'),
]

apps/sendbox/urls.py
from django.conf.urls import url
from apps.sendbox.views import EmailCreateView, StaticCampaignSetUpView,\
    EmailTemplateListView, EmailTemplateUpdateView

urlpatterns = [
    url(r'^mail-launch/', EmailCreateView.as_view(), name="email_create"),
    url(r'^campaign-setup/', StaticCampaignSetUpView.as_view(), name="campaign_setup"),
    url(r'^template-list/$', EmailTemplateListView.as_view(), name='template_list'),
    url(r'^(?P<slug>[-\w]+)/$', EmailTemplateUpdateView.as_view(), name='template_update'),
]

new_djangoteam/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.views.decorators.gzip import gzip_page
from django.views.generic import TemplateView
from apps import contact_us
from apps.accounts import views
from django.contrib.auth import views as auth_views
from apps.faq.views import PermissionView
from apps.site_admin.models import AboutUs
from apps.site_admin.views import AboutUsView
from home import views
from apps.contact_us import views as contact

from django.views.defaults import server_error, page_not_found,permission_denied

page_not_found = 'apps.freelancers.views.handler404'
server_error = 'apps.freelancers.views.handler500'



urlpatterns = [

    url(r'^site_administration/', include(admin.site.urls)),
    url(r'^$', gzip_page(views.IndexView.as_view()), name='IndexView'),
    # url(r'^register',views.RegisterView.as_view(), name='Register'),
    url(r'^accounts/', include('apps.accounts.urls')),
    url(r'^', include('apps.clients.urls')),
    url(r'^blogs/', include('apps.blogs.urls')),
    url(r'^faq/', include('apps.faq.urls')),
    url(r'^profile/', include('apps.profile.urls')),
    url(r'^', include('apps.freelancer.urls')),
    url(r'^about/$',AboutUsView.as_view(),name='about'),
    url(r'^contact/$',contact.ContactView.as_view(), name='contact_us'),
    url(r'^admin/mail/', include('apps.sendbox.urls')),
    url(r'^site_admin/', include('apps.site_admin.urls')),
    url(r'^permission_error/$', PermissionView.as_view(), name='permission_error'),
    url(r'^hire/', include('apps.hire.urls')),


    url(r'^password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': 'auth_password_reset_done',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': 'auth_password_reset_complete'},
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        name='auth_password_reset_complete'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name='auth_password_reset_done'),

        #####CKEditor #####
    url(r'^ckeditor/', include('ckeditor.urls')),


]


if 'django_comments' in settings.INSTALLED_APPS:
    # Django 1.7/1.8 situation
    COMMENT_URLS = 'django_comments.urls'


urlpatterns += patterns('',
                        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                            {'document_root': settings.STATIC_ROOT, 'show_indexes': False}),
                        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                            {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
                        url(r'^comments/', include(COMMENT_URLS)),
                        )
urlpatterns += staticfiles_urlpatterns()

apps/freelancer/models.py
from __future__ import unicode_literals

from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from django.db import models


from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill


class Company(models.Model):
    """
    Freelancer Company Name model
    """
    company_name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.company_name


class WorkCategories(models.Model):
    """
    Freelancer Work Categories model.
    """
    category_title = models.CharField(_('Work Category name'), max_length=255)

    def __unicode__(self):
        return self.category_title

    class Meta:
        verbose_name = "Work Category"
        verbose_name_plural = "Work Categories"


class WorkSubCategories(models.Model):
    """
    Freelancer Work SubCategories model
    """
    work_category = models.ForeignKey(WorkCategories,related_name='work_sub_categories',
                                      verbose_name="Work Sub Categories")
    sub_category_title = models.CharField(_('Sub category title'), max_length=255)

    def __unicode__(self):
        return self.sub_category_title

    class Meta:
        verbose_name = "Work Sub Category"
        verbose_name_plural = "Work Sub Categories"


class ExperienceLevel(models.Model):
    """
    Freelancer Experience Level model
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='experience_level',
                             verbose_name="Experience Level")
    exp_level_type = models.CharField(_('Experience Level title'), max_length=255)

    def __unicode__(self):
        return self.exp_level_type

    class Meta:
        verbose_name = "Experience Level"
        verbose_name_plural = "Experience Levels"


class EmploymentHistory(models.Model):
    """
    Freelancer Employment History
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='employment_history',
                             verbose_name="Employment history")
    company = models.ForeignKey(Company,)
    location = models.CharField(_('Location'), max_length=255)
    role = models.CharField(_('Role'), max_length=255)
    start_date = models.DateField(_('Start date'), max_length=255)
    end_date = models.DateField(_('End date'), max_length=255)
    description = models.TextField(_('Description'))

    def __unicode__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = "Employment History"
        verbose_name_plural = "Employment Histories"


class EducationDetails(models.Model):
    """
     Freelancer Education Details model
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='education_details',
                             verbose_name="Education details")
    institution_name = models.CharField(_('Institution Name'), max_length=255)
    degree = models.ForeignKey('knowledgebase.DegreeCourse', verbose_name='Degree')
    area_of_study = models.CharField(_('Area of study'), max_length=255)
    enrollment_date = models.DateField(_('Enrollment Date'), max_length=255)

    def __unicode__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = "Education Detail"
        verbose_name_plural = "Education Details"


class Certifications(models.Model):
    """
     Freelancer Certifications model
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='cerifications',
                             verbose_name="Certifications")
    certificate_name = models.CharField(_('Certificate name'), max_length=255)
    issued_by = models.CharField(_('Issued authority'), max_length=255, blank=True, null=True)
    certificate = models.ImageField(_('Certificate'), upload_to='certificates_upload')
    certificate_thumbnail = ImageSpecField(source='certificate',processors=[ResizeToFill(370, 200)], format='JPEG',options={'quality': 60})


    def __unicode__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = "Certifications"
        verbose_name_plural = "Certifications"


class HourlyRate(models.Model):
    """
    Freelancer Hourly Rate model
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='hourly_rate',
                                verbose_name="Hourly Rate")
    hourly_rate = models.DecimalField(_('Hourly rate'),max_digits=5, decimal_places=2)
    actual_rate = models.DecimalField(_('Actual rate'),  max_digits=5, decimal_places=2)

    def __unicode__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = "Hourly rate"
        verbose_name_plural = "Hourly rates"


class FreelancerPortfolio(models.Model):
    """
    Freelancer Portfolio model
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='portfolio',
                                verbose_name="Portfolio")
    project_name = models.CharField(_('Project name'), max_length=255)
    description = models.TextField(_('Description'))
    project_url = models.URLField(_('Project URL'))
    main_category = models.ForeignKey(WorkCategories, related_name='portfolio_work_categories',
                                      verbose_name="Work Categories")
    sub_category = models.ManyToManyField(WorkSubCategories,verbose_name='Work Sub Category',related_name='portfolio_sub_category')
    skills = models.ManyToManyField('knowledgebase.Skills', verbose_name='Skills', related_name='portfolio_skills')

    def __unicode__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = "Freelancer portfolio"
        verbose_name_plural = "Freelancer portfolios"


class Availability(models.Model):
    """
    Freelancer Availability model
    """
    periods = (
        ('full_time', 'full_time'),
        ('weekly', 'weekly'),
    )
    statusChoice = (
        ('available', 'available'),
        ('not_available', 'not_available'),
    )


    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='availability_user',
                                verbose_name="Avalability user")
    status = models.CharField(_('Status'),max_length=100,choices=statusChoice)
    period = models.CharField(_('Period'),max_length=100,choices=periods,null=True,blank=True)
    avalable_hours = models.CharField(_('avalable hours'),null=True,blank=True,max_length=3)

    def __unicode__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = "Freelancer Avalability"
        verbose_name_plural = "Freelancer Avalabilities"

apps/freelancer/templates/profile/ajax/Create_profile/certification_form.html
<div class="profile_formSection certficationFormSection">
    <form role="form" id="CertificationForm" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="certification_action" id="certification_action" value="add_certification">
        <div class="profile-edit-rate-level">
            <h3 class="profile-experience sub_head_create">Certification</h3>
            <p class="profile-accordian"><span><i id="certification-open-add" class="fa fa-plus-circle"></i></span><span class="box_label_align">Add Certification</span></p>
            <div class="profile-accordian-details">
                <div class="certification_form">
                    <div class="profile-edit-rate-level CertficationFormContainer">
                        <div class="profile-edit-form-group clearfix">
                            <div class="profile-edit-label profile-label-align">
                                <label>Certification name</label>
                            </div>
                            <div class="profile-edit-input">
                                {{ form_certifications.certificate_name }}
                            </div>
                             <div class="clear"></div>
                        </div>
                        <div class="profile-edit-form-group clearfix">
                            <div class="profile-edit-label profile-label-align">
                                <label>Issued by</label>
                            </div>
                            <div class="profile-edit-input">
                                {{ form_certifications.issued_by }}
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="profile-edit-form-group clearfix">
                            <div class="profile-edit-label profile-label-align">
                                <label>Certification</label>
                            </div>
                            <div class="profile-edit-input">
                                <input id="id_certificate" name="certificate" type="file" onchange="readURL(this);">
                                {% if certificate_instance.certificate %}
                                <span><img src="{{certificate_instance.certificate_thumbnail.url}}" id="current_certificate"></span>
                                {% else %}
                                <span><img src="" id="current_certificate"></span>
                                {% endif %}
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                    <button type="button" class="btn-company-save save_certification_add" onclick = "addCertification();">Save</button>
                    <button type="button" class="btn-company-save save_n_add" onclick = "Save_addCertification();">Save & add</button>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#current_certificate').attr('src', e.target.result);
                $('#current_certificate').show();;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }


</script>

apps/freelancer/templates/profile/ajax/Create_profile/education_detail.html
<div class="profile_formSection educationFromContainer">
    <form role="form" id="EducationForm">{% csrf_token %}
        <input type="hidden" name="education_action" id="education_action" value="add_education">
        <div class="profile-edit-rate-level">
            <h3 class="profile-experience sub_head_create">Education Details</h3>
            <p class="profile-accordian"><span><i id ="education-open-add" class="fa fa-plus-circle"></i><span class="box_label_align">Add your Education Details</span></span></p>
            <div class="profile-accordian-details">
                <div class="profile-edit-form-group EducationFormContainer">
                    <div class="profile-edit-rate-level form_align_company education_form_align">
                        <div class="profile-edit-label profile-edit-education">
                            <label>Institution Name</label>
                        </div>
                        <div class="eduction_input profile-edit-input profile-edit-education-input">
                            {{form_education.institution_name}}
                        </div>
                        <div class="clear"></div>
                        <div>
                            <span class="profile-edit-label profile-edit-education">
                                <label>Enrollment Date</label>
                            </span>
                            <div class="eduction_date_input profile-edit-input-date">
                                {{form_education.enrollment_date}}
                            </div>
                            <span class="profile-edit-label-date">
                                <label>Degree</label>
                            </span>
                            <div class="profile-edit-input-date">
                                {{form_education.degree}}
                                <div class="clear"></div>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                        <div class="profile-edit-label profile-edit-education">
                            <label>Area of study</label>
                        </div>
                        <div class="eduction_input profile-edit-input  profile-edit-education-input">
                            {{form_education.area_of_study}}
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
                <button type="button" class="btn-company-save save_education_add" onclick="addEducationDetails();">Save</button>
                <button type="button" class="btn-company-save  save_n_add" onclick="addSaveEducationDetails();">Save & add</button>
                <div class="clear"></div>
           </div>
        </div>
    </form>
</div>

apps/freelancer/templates/profile/ajax/Create_profile/emp_history.html
<div class="profile_formSection experienceFormContainer">

    <form role="form" id="registerExperienceForm">{% csrf_token %}
        <input type="hidden" name="employment_action" id="employment_action" value="add_history">

        <div class="profile-edit-rate-level">
            <h3 class="profile-experience sub_head_create">Employment History</h3>

            <p class="profile-accordian"><span><i id="employee-open-add" class="fa fa-plus-circle"></i><span
                    class="box_label_align">Add your Employment History (Optional)</span></span></p>

            <div class="profile-accordian-details">
                <div class="profile-edit-form-group ">
                    <div class="profile-edit-rate-level form_align_company FormContainer">
                        <div class="profile-edit-label company_details">
                            <label>Company</label>
                        </div>
                        <div class="employement_input profile-edit-input profile-edit-rate-input"
                             id="normal-Company-section">
                            <span class="profile-add " id="addCompany"><i class="fa fa-plus-circle "></i></span>
                            <input type="text" id="search-box" value="{{company_name}}" autocomplete="off" name="company_name"/>

                            <div id="suggesstion-box"></div>
                            <div style="display:none">
                                <input id="autocomplete2-value" type="text" name="code"/>
                            </div>
                        </div>
                        <div class="profile-edit-input" id="add-Company-section">
                            <span class="profile-close" id="close-Company">New Company <i class="fa fa-times "></i></span>
                            <span class="profile-add " id="add-Company" onclick="company_add();"><i
                                    class="fa fa-plus-circle "></i></span>
                            <input type="text" id="company_name_add"/>
                        </div>
                        <div class="clear"></div>
                        <div class="profile-edit-label company_details">
                            <label>Location</label>
                        </div>
                        <div class="employement_input profile-edit-input profile-edit-rate-input">
                            {{ form_employment.location }}
                        </div>
                        <div class="clear"></div>
                        <div class="profile-edit-label company_details">
                            <label>Role</label>
                        </div>
                        <div class="employement_input profile-edit-input profile-edit-rate-input">
                            {{ form_employment.role }}
                        </div>
                        <div class="clear"></div>
                        <div class="date_container">
                                <span class="profile-edit-label company_details">
                                    <label>Start Date</label>
                                </span>

                            <div class="profile-edit-input-date profile-edit-rate-date">
                                {{ form_employment.start_date }}
                            </div>
                                <span class="profile-edit-label-date">
                                    <label>End Date</label>
                                </span>

                            <div class="profile-edit-input-date">
                                {{ form_employment.end_date }}
                            </div>

                            <div class="clear"></div>
                        </div>
                        <div class="profile-edit-label company_details">
                            <label>Description</label>
                        </div>
                        <div class="employement_input profile-edit-input profile-edit-rate-input">
                            {{ form_employment.description }}
                        </div>
                        <div class="clear"></div>
                    </div>
                    <button type="button" class="btn-company-save save_history_add" onclick="registerEmploymentHistory();">Save</button>
                    <button type="button" class="btn-company-save save_n_add" onclick="addEmploymentHistory();">Save & Add</button>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    //***************************Cancel Edit***************************

</script>

apps/freelancer/templates/profile/ajax/Create_profile/portfolio_form.html
<div class="profile_formSection portfolio_sec">
    <form role="form" id="addPortfolioForm" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="portfolio_action" id="portfolio_action" value="add_portfolio">
        <div class="profile-edit-rate-level">
            <h3 class="profile-experience sub_head_create">Portfolio</h3>
            <p class="profile-accordian"><span><i id="Portfolio-open-add" class="fa fa-plus-circle"></i></span><span class="box_label_align">Add Portfolio</span></p>
            <div class="profile-accordian-details ">
                <div class="profile-edit-rate-level PortfolioFormContainer">
                    <div class="profile-edit-form-group">
                        <div class="profile-edit-label">
                            <label>Project name</label>
                        </div>
                        <div class="profile-edit-input">
                            {{ form_portfolio.project_name }}
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="profile-edit-form-group">
                        <div class="profile-edit-label">
                            <label>Description</label>
                        </div>
                        <div class="profile-edit-input">
                            {{ form_portfolio.description }}
                        </div>
                        <div class="clear"></div>
                    </div>
                     <div class="profile-edit-form-group">
                        <div class="profile-edit-label">
                            <label>Work Category</label>
                        </div>
                        <div class="profile-edit-input portfolio_category_align" onclick="work_category('portfolio');">
                            {{ form_portfolio.main_category }}

                        </div>
                    </div>
                    <div class="category_holder ">
                        <div class="profile-edit-form-group">
                            <div class="profile-edit-label">
                                <label>Sub Category</label>
                            </div>
                            <div class="profile-edit-input">
                                    <select  class="multi_select portfolio_dropdown " name="sub_category"  multiple="multiple">
                                    {% for sub_category in portfolio_instance.sub_category.all %}
                                        <option selected="selected" value="{{sub_category}}">{{sub_category.sub_category_title}} </option>
                                    {% endfor %}

                                </select>
                            </div>
                        </div>
                        <div class="profile-edit-form-group">
                            <div class="profile-edit-label">
                                <label>Skills</label>
                            </div>
                            <div class="profile-edit-input">
                            <select class="multi_select portfolio_dropdown " name="skills"  multiple="multiple">
                                    {% for skill in portfolio_instance.skills.all %}
                                        <option selected="selected" value="{{skill.id}}">{{skill.skill_name}} </option>
                                    {% endfor %}
                            </select>
                            </div>
                        </div>
                    </div>
                    <div class="profile-edit-form-group">
                        <div class="profile-edit-label">
                            <label>Project Url</label>
                        </div>
                        <div class="profile-edit-input">
                            {{ form_portfolio.project_url }}
                        </div>
                    </div>

                     <div class="clear"></div>
                </div>
                <button type="button" class="btn-company-save save_portfolio_add " onclick="addPortfolio();" >Save</button>
                <button type="button" class="btn-company-save save_n_add" onclick="addSavePortfolio();" >Save & add</button>
                <div class="clear"></div>
            </div>
        </div>
    </form>
</div>
<!--
<script>
    $('.multi_select').tokenize({
        displayDropdownOnFocus: true,
    });
</script>-->