apps/clients/urls.py
from django.conf.urls import url
from django.views.decorators.gzip import gzip_page

from apps.clients.views import PostJobView,  ClientProfileView, FindJobView, FindDetailsView, ClientDetailList,\
    JobDetailView, FreelancerActiveView, MyJobView, MyJobDetails, FetchJobDetailsView,InviteValidation, ChatView
from apps.freelancer.general import check_group_required


urlpatterns = [
    url(r'^jobpost/', gzip_page(PostJobView.as_view()), name='post-job'),
    url(r'^jobs/', gzip_page(FindJobView.as_view()), name='find_job'),
    url(r'^my-jobs/', gzip_page(MyJobView.as_view()), name='my_jobs'),
    url(r'^my-jobsDetails/(?P<slug>[\w-]+)', gzip_page(check_group_required(MyJobDetails.as_view())), name='my_jobsDetails'),
    url(r'^client-detail/', gzip_page(check_group_required(ClientDetailList.as_view())),name='client-detail'),
    url(r'^job-list-detail/(?P<slug>[\w-]+)', gzip_page(FindDetailsView.as_view()),name='find_job_details'),
    url(r'^client-profile/$', ClientProfileView.as_view(), name='client_profile'),
    url(r'^job-details/(?P<slug>[\w-]+)', gzip_page(JobDetailView.as_view()), name='job_details'),
    url(r'^client-freelancer/', FreelancerActiveView.as_view(), name='freelancer_active'),
    url(r'^fetch_job_details/', gzip_page(FetchJobDetailsView.as_view()), name='fetch_job_details'),
    url(r'^is_invited/', InviteValidation.as_view(), name='is_invited'),
    url(r'^message/', ChatView.as_view(), name='chat_view'),


    ]

apps/hire/urls.py
from django.conf.urls import url
from apps.hire.views import HireView, HireEditAddView, ContractListView, FreelancerContractView

urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/(?P<slug1>[-\w]+)/$', HireView.as_view(), name='hire'),
    url(r'^hire_add_edit/$', HireEditAddView.as_view(), name='add_edit_hire'),
    url(r'^contracts/$', ContractListView.as_view(), name='contract'),
    url(r'^freelancer_contract/(?P<slug>[-\w]+)/(?P<slug1>[-\w]+)/$', FreelancerContractView.as_view(), name='freelancer_contract'),
]

apps/sendbox/urls.py
from django.conf.urls import url
from apps.sendbox.views import EmailCreateView, StaticCampaignSetUpView,\
    EmailTemplateListView, EmailTemplateUpdateView

urlpatterns = [
    url(r'^mail-launch/', EmailCreateView.as_view(), name="email_create"),
    url(r'^campaign-setup/', StaticCampaignSetUpView.as_view(), name="campaign_setup"),
    url(r'^template-list/$', EmailTemplateListView.as_view(), name='template_list'),
    url(r'^(?P<slug>[-\w]+)/$', EmailTemplateUpdateView.as_view(), name='template_update'),
]

new_djangoteam/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.views.decorators.gzip import gzip_page
from django.views.generic import TemplateView
from apps import contact_us
from apps.accounts import views
from django.contrib.auth import views as auth_views
from apps.faq.views import PermissionView
from apps.site_admin.models import AboutUs
from apps.site_admin.views import AboutUsView
from home import views
from apps.contact_us import views as contact

from django.views.defaults import server_error, page_not_found,permission_denied

page_not_found = 'apps.freelancers.views.handler404'
server_error = 'apps.freelancers.views.handler500'



urlpatterns = [

    url(r'^site_administration/', include(admin.site.urls)),
    url(r'^$', gzip_page(views.IndexView.as_view()), name='IndexView'),
    # url(r'^register',views.RegisterView.as_view(), name='Register'),
    url(r'^accounts/', include('apps.accounts.urls')),
    url(r'^', include('apps.clients.urls')),
    url(r'^blogs/', include('apps.blogs.urls')),
    url(r'^faq/', include('apps.faq.urls')),
    url(r'^profile/', include('apps.profile.urls')),
    url(r'^', include('apps.freelancer.urls')),
    url(r'^about/$',AboutUsView.as_view(),name='about'),
    url(r'^contact/$',contact.ContactView.as_view(), name='contact_us'),
    url(r'^admin/mail/', include('apps.sendbox.urls')),
    url(r'^site_admin/', include('apps.site_admin.urls')),
    url(r'^permission_error/$', PermissionView.as_view(), name='permission_error'),
    url(r'^hire/', include('apps.hire.urls')),


    url(r'^password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': 'auth_password_reset_done',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': 'auth_password_reset_complete'},
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        name='auth_password_reset_complete'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name='auth_password_reset_done'),

        #####CKEditor #####
    url(r'^ckeditor/', include('ckeditor.urls')),


]


if 'django_comments' in settings.INSTALLED_APPS:
    # Django 1.7/1.8 situation
    COMMENT_URLS = 'django_comments.urls'


urlpatterns += patterns('',
                        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                            {'document_root': settings.STATIC_ROOT, 'show_indexes': False}),
                        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                            {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
                        url(r'^comments/', include(COMMENT_URLS)),
                        )
urlpatterns += staticfiles_urlpatterns()

apps/hire/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django_countries import settings
import datetime
from django.utils.translation import ugettext_lazy as _
from django.utils.crypto import get_random_string
from django.utils.text import slugify
# Create your models here.
from apps.clients.models import ClientJobs
from apps.freelancer.models import WorkCategories, WorkSubCategories
from apps.profile.models import FreelancerProfile, ClientProfile


class JobsMilestone(models.Model):
    """
       Job Milestone model.
    """
    MILESTONE_STATUS = (
        ('APPROVED', 'Approved'),
        ('PENDING', 'Pending'),
        ('HOLD', 'Hold'),
    )
    milestone_title = models.CharField(_('Milestone Title'), max_length=255)
    milestone_description = models.TextField(_('Milestone Description'), validators=[MinLengthValidator(00)])
    start_date = models.DateField(_('Milestone start date'), max_length=255, default=datetime.date.today)
    close_date = models.DateField(_('Milestone close date'), max_length=255, default=datetime.date.today)
    rate = models.IntegerField(_('Hire Payment'), default=0)
    rate_change = models.IntegerField(_('Hire Payment'), default=0, null=True, blank=True)
    status = models.CharField(max_length=10, choices=MILESTONE_STATUS, default='PENDING',
                              verbose_name="Milestone status")
    def __str__(self):
        return self.milestone_title

    class Meta:
        verbose_name = "Milestone"
        verbose_name_plural = "Milestones"
        default_permissions = ('add', 'change', 'delete', 'view')


class HiredJobsContract(models.Model):
    """
    Hire Jobs model.
    """
    STATUS = (
        ('APPROVED', 'Approved'),
        ('PENDING', 'Pending'),
        ('HOLD', 'Hold'),
    )
    PAYMENT_TYPE = (
        ('Fixed', 'Fixed'),
        ('Hourly', 'Hourly'),
    )
    client_job = models.ForeignKey(ClientJobs, related_name='hire_jobs', verbose_name="Client Job")
    freelancer_profile = models.ForeignKey(FreelancerProfile, related_name='hire_freelancer',
                                           verbose_name="Hired Freelancer")
    client_profile = models.ForeignKey(ClientProfile, related_name='hire_client', verbose_name="Hired Client")
    job_title = models.CharField(_('Hire Job title'), max_length=255)
    job_number = models.IntegerField(_('Hire Job Number'), default=0)
    job_main_category = models.ForeignKey(WorkCategories, related_name='hire_job_main_category',
                                          verbose_name="Hire Job Category")
    job_description = models.TextField(_('Hire Job Description'), validators=[MinLengthValidator(00)])
    payment_type = models.CharField(_('Hire PaymentType'), max_length=10, choices=PAYMENT_TYPE, default='Fixed',)
    payment = models.IntegerField(_('Hire Payment'), default=0)

    company = models.CharField(_('Company Name'), null=True, max_length=255, default='')

    milestone = models.ManyToManyField(JobsMilestone, related_name='hire_job_sub_category',
                                       verbose_name="Jobs Milestone", blank=True)

    slug = models.SlugField(max_length=255, unique=True,auto_created=True,editable=False)
    status = models.CharField(max_length=10, choices=STATUS, default='PENDING',
                              verbose_name="contract status")
    change_made_client = models.BooleanField(default=False)
    change_rate_flag = models.BooleanField(default=False)

    def __str__(self):
        return "{0}::{1}".format(self.client_job.user.username, self.freelancer_profile.user.username)

    def save(self, *args, **kwargs):
        super(HiredJobsContract, self).save(*args, **kwargs)
        if not self.slug:
            unique_id = get_random_string(length=15)
            self.slug = slugify(self.job_title) + "-" + unique_id
            self.save()

    class Meta:
        verbose_name = "HireJob"
        verbose_name_plural = "HireJobs"
        default_permissions = ('add', 'change', 'delete', 'view')


class HiredJobHistory(models.Model):
    HISTORY_STATUS = (
        ('CHANGE_REQUEST', 'Change'),
        ('APPROVED', 'Approved'),
        ('PENDING', 'Pending'),
    )
    hire_job = models.ForeignKey(HiredJobsContract, related_name='hire_job', verbose_name="Hire Job")

    client_user = models.ForeignKey(ClientProfile, related_name='hire_client_user',
                                    verbose_name="client_user")
    freelancer_user = models.ForeignKey(FreelancerProfile, related_name='hire_freelancer_user',
                                        verbose_name="freelancer_user", null=True)

    post_date = models.DateTimeField(verbose_name='Date', auto_now_add=True)
    status = models.CharField(max_length=10, choices=HISTORY_STATUS, default='PENDING',
                              verbose_name="contract status")
    rate_change = models.IntegerField(_('Rate Change'), default=0)
    comment = models.TextField(verbose_name='comment', blank=True, null=True)

    def __str__(self):
        return "{0}::{1}::{2}".format(self.hire_job.job_title, self.client_user.user.username,
                                      self.post_date)

    class Meta:
        verbose_name = "Hired Job History"
        verbose_name_plural = "Hired Job Histories"
        default_permissions = ('add', 'change', 'delete', 'view')

apps/hire/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.forms import ModelForm
from django.utils.crypto import get_random_string
from django.utils.text import slugify
from apps.hire.models import HiredJobsContract, JobsMilestone


class HiredJobsContractForm(ModelForm):
    """
    Form for hire
    """

    class Meta:
        model = HiredJobsContract
        exclude = ['status']

    def __init__(self, *args, **kwargs):
        super(HiredJobsContractForm, self).__init__(*args, **kwargs)

        # for field in self.fields:
        #     self.fields['first_name'].widget.attrs['readonly'] = 'readonly'
        #     self.fields['last_name'].widget.attrs['readonly'] = 'readonly'
        #     self.fields['email'].widget.attrs['readonly'] = 'readonly'

    def save(self, commit=True):
        hire = super(HiredJobsContractForm, self).save(commit=False)
        if commit:
            hire.save()
        return hire


class JobsMilestoneForm(forms.ModelForm):
    """
    Form to add add milestone
    """

    class Meta:
        model = JobsMilestone
        exclude = ['status']

    def __init__(self, *args, **kwargs):
        super(JobsMilestoneForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget.attrs['class'] = 'datepicker milestone_edit_start_date'
        self.fields['close_date'].widget.attrs['class'] = 'datepicker milestone_edit_end_date'
        self.fields['milestone_description'].widget.attrs['rows'] = '3'


    def save(self, commit=True):
        milestone = super(JobsMilestoneForm, self).save(commit=False)
        if commit:
            milestone.save()
        return milestone


class ChangesMilestoneRateForm(forms.ModelForm):
    """
    Form to add add milestone
    """

    class Meta:
        model = JobsMilestone
        exclude = ['status']

    def __init__(self, *args, **kwargs):
        super(ChangesMilestoneRateForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget.attrs['readonly'] = 'readonly'
        self.fields['milestone_title'].widget.attrs['readonly'] = 'readonly'
        self.fields['close_date'].widget.attrs['readonly'] = 'readonly'
        self.fields['milestone_description'].widget.attrs['rows'] = '3'
        self.fields['milestone_description'].widget.attrs['readonly'] = 'readonly'
        self.fields['rate'].widget.attrs['readonly'] = 'readonly'

    def save(self, commit=True):
        milestone = super(ChangesMilestoneRateForm, self).save(commit=False)
        if commit:
            milestone.save()
        return milestone

apps/hire/templates/ajax/edit_milestone.html
<div class="modal milestone_edit_modal modal_terms_condition">
    <div class="milestone_modal">
        <div class="modal-content">
            <span class="pull-right modal-close " onclick="modal_conditions_close()">X</span>

            <div class="actionheading "><span class="pull-right modal-close "
                                              onclick="modal_conditions_close()">X</span></div>
            <h4 class="text-center modal_main_head"><span>Edit Milestone</span></h4>
             <form role="form" id="milestone_edit_form" >
                 <input type="hidden" class="hire_id" name="hire_id" value="{{ hire.id }}">
                 <input type="hidden" name="milestone_edit_id" id="milestone_edit_id" value="{{ milestone.id }}">
                <div class="milestone_modal_container">
                    <div class="full-width">
                        <label>Title</label>
                        {{ milestone_form.milestone_title }}
                    </div>
                    <div class="full-width">
                        <label>Description</label>
                        {{ milestone_form.milestone_description }}
                    </div>
                    <div class="full-width">
                        <div class="column-left milestone_date">
                            <label>Start Date</label>
                            {{ milestone_form.start_date }}
                        </div>
                        <div class="column-center milestone_date">
                            <label>End Date</label>
                            {{ milestone_form.close_date }}
                        </div>
                        <div class="column-right milestone_date">
                            <label>Rate</label>
                            {{ milestone_form.rate }}
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
                <div class="hire_request_btn_holder">
                    <button type="button" class="hire_request_btn color-blue milestone_edit_submit">SUBMIT</button>
                </div>
             </form>
             <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
</div>

    {% block extra_js %}

     <script>
    $(document).on('click','.milestone_edit_submit',function() {
        var milestone_id = $('#milestone_edit_id').val();
        var edit = "milestone_row_"+ milestone_id ;
        var data = $('#milestone_edit_form').serialize();
        $.ajax({
            url: "{% url 'add_edit_hire' %}",
            type: 'POST',
            data: data+"&action=edit",
            beforeSend: function() {
              loaderShow();
            },
            success: function (response_data)
             {
                 if (response_data.status==true)
                    {
                        var rate = $('#id_rate').val();
                        var milestone_title = $('#id_milestone_title').val();
                        $("#"+edit +" .milestone_name").text(milestone_title);
                        $("#"+edit +" .rate").text(rate);
                        modal_conditions_close();
                        loaderHide();
                    }

             },
             errors:function (return_data){ console.log("Error");}
        });

    });


$(function() {
                var dateToday = new Date();
                $( ".datepicker" ).datepicker({
                    changeMonth: true,
                    changeYear: true,
                    minDate: dateToday,
                    altFormat: "yy-mm-dd",
                    dateFormat: 'yy-mm-dd',
                });
            });


            $(function() {
                var dateToday = new Date();
                $( ".milestone_start_date" ).datepicker({
                    changeMonth: true,
                    changeYear: true,
                    minDate: dateToday,
                    altFormat: "yy-mm-dd",
                    dateFormat: 'yy-mm-dd',
                });
            });
            </script>
            {% endblock %}

apps/hire/templates/ajax/freelancer_contract_milestone_list.html
 <div  class="milestone_table">
{% for milestone in hire.milestone.all %}

    <div class="milestone_row" id="milestone_row_{{ milestone.id }}">
        <div class="milestone_td">{{ forloop.counter }}</div>
        <div class="milestone_td milestone_name">{{milestone.milestone_title}}</div>
        <div class="milestone_td milestone_small rate">${{milestone.rate}}
            {% if milestone.status = 'APPROVED' %}
                <i class="fa fa-check-circle-o color-green" aria-hidden="true" title="milestone approved"></i>
            {% endif %}
        </div>
        <div class="milestone_td milestone_small">2 days ago</div>
        <div class="milestone_td milestone_action_td"><i class="fa fa-commenting" aria-hidden="true"> 4</i></div>
        <div class="milestone_td milestone_action_td"><i class="fa fa-pencil-square-o" aria-hidden="true" onclick="rateChangeRequest({{ milestone.id }})"></i></div>
        <div class="milestone_td milestone_action_td"><i class="fa fa-thumbs-up" aria-hidden="true" title="deal rate"></i></div>
        <div class="clearfix"></div>
    </div>

{% endfor %}
 </div>

apps/hire/templates/ajax/milestone_change_request.html
<div class="modal milestone_change_request_modal ">
    <div class="milestone_modal">
        <div class="modal-content">
            <span class="pull-right modal-close " onclick="modal_changeRate_close()">X</span>

            <div class="actionheading "><span class="pull-right modal-close "
                                              onclick="modal_changeRate_close()">X</span></div>
            <h4 class="text-center modal_main_head"><span>Edit Milestone</span></h4>
             <form role="form" id="milestone_edit_form" >
                 <input type="hidden" class="hire_id" name="hire_id" value="{{ hire.id }}">
                 <input type="hidden" name="milestone_edit_id" class="milestone_edit_id" value="{{ milestone.id }}">
                <div class="milestone_modal_container">
                    <div class="full-width">
                        <label>Title</label>
                        {{ milestone_form.milestone_title }}
                    </div>
                    <div class="full-width">
                        <label>Description</label>
                        {{ milestone_form.milestone_description }}
                    </div>
                    <div class="full-width">
                        <div class="semi_width">
                             <div class="pull-left semi_width_holder">
                                <label>Start Date</label>
                                {{ milestone_form.start_date }}
                             </div>
                        </div>
                        <div class="semi_width">
                            <div class=" pull-right semi_width_holder">
                                <label>End Date</label>
                                {{ milestone_form.close_date }}
                            </div>
                        </div>
                    </div>
                     <div class="full-width">
                        <div class="semi_width">
                            <div class="pull-left semi_width_holder">
                                <label>Rate</label>
                                {{ milestone_form.rate }}
                            </div>
                        </div>
                         <div class="semi_width">
                             <div class=" pull-right semi_width_holder">
                                 <label>Changed Rate</label>
                                <input id="id_rate_change" name="rate_change" type="number" value="">
                             </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
                <div class="hire_request_btn_holder">
                    <button type="button" class="hire_request_btn color-blue rateChangeBtn">SUBMIT</button>
                </div>
             </form>
             <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
</div>

    {% block extra_js %}

     <script>




            </script>
            {% endblock %}

apps/hire/templates/ajax/milestone_list.html
 <div  class="milestone_table">
{% for milestone in hire.milestone.all %}

    <div class="milestone_row" id="milestone_row_{{ milestone.id }}">
        <div class="milestone_td">{{ forloop.counter }}</div>
        <div class="milestone_td milestone_name">{{milestone.milestone_title}}</div>
        <div class="milestone_td milestone_small rate">${{milestone.rate}}
            {% if milestone.status = 'APPROVED' %}
                <i class="fa fa-check-circle-o color-green" aria-hidden="true" title="milestone approved"></i>
            {% endif %}
        </div>
        <div class="milestone_td milestone_small">2 days ago</div>
        <div class="milestone_td milestone_action_td"><i class="fa fa-commenting" aria-hidden="true"> 4</i></div>
        <div class="milestone_td milestone_action_td"><i class="fa fa-pencil-square-o" aria-hidden="true" onclick="edit_milestone({{ milestone.id }})" title="View/Edit"></i></div>
        <div class="milestone_td milestone_action_td "><i class="fa fa-trash-o" onclick="delete_milestone({{ milestone.id }})" aria-hidden="true" title="Delete"></i></div>
        <div class="clearfix"></div>
    </div>

{% endfor %}
 </div>