apps/clients/urls.py
from django.conf.urls import url
from django.views.decorators.gzip import gzip_page

from apps.clients.views import PostJobView,  ClientProfileView, FindJobView, FindDetailsView, ClientDetailList,\
    JobDetailView, FreelancerActiveView, MyJobView, MyJobDetails, FetchJobDetailsView,InviteValidation, ChatView
from apps.freelancer.general import check_group_required


urlpatterns = [
    url(r'^jobpost/', gzip_page(PostJobView.as_view()), name='post-job'),
    url(r'^jobs/', gzip_page(FindJobView.as_view()), name='find_job'),
    url(r'^my-jobs/', gzip_page(MyJobView.as_view()), name='my_jobs'),
    url(r'^my-jobsDetails/(?P<slug>[\w-]+)', gzip_page(check_group_required(MyJobDetails.as_view())), name='my_jobsDetails'),
    url(r'^client-detail/', gzip_page(check_group_required(ClientDetailList.as_view())),name='client-detail'),
    url(r'^job-list-detail/(?P<slug>[\w-]+)', gzip_page(FindDetailsView.as_view()),name='find_job_details'),
    url(r'^client-profile/$', ClientProfileView.as_view(), name='client_profile'),
    url(r'^job-details/(?P<slug>[\w-]+)', gzip_page(JobDetailView.as_view()), name='job_details'),
    url(r'^client-freelancer/', FreelancerActiveView.as_view(), name='freelancer_active'),
    url(r'^fetch_job_details/', gzip_page(FetchJobDetailsView.as_view()), name='fetch_job_details'),
    url(r'^is_invited/', InviteValidation.as_view(), name='is_invited'),
    url(r'^message/', ChatView.as_view(), name='chat_view'),


    ]

apps/sendbox/urls.py
from django.conf.urls import url
from apps.sendbox.views import EmailCreateView, StaticCampaignSetUpView,\
    EmailTemplateListView, EmailTemplateUpdateView

urlpatterns = [
    url(r'^mail-launch/', EmailCreateView.as_view(), name="email_create"),
    url(r'^campaign-setup/', StaticCampaignSetUpView.as_view(), name="campaign_setup"),
    url(r'^template-list/$', EmailTemplateListView.as_view(), name='template_list'),
    url(r'^(?P<slug>[-\w]+)/$', EmailTemplateUpdateView.as_view(), name='template_update'),
]

new_djangoteam/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.views.decorators.gzip import gzip_page
from django.views.generic import TemplateView
from apps import contact_us
from apps.accounts import views
from django.contrib.auth import views as auth_views
from apps.faq.views import PermissionView
from apps.site_admin.models import AboutUs
from apps.site_admin.views import AboutUsView
from home import views
from apps.contact_us import views as contact

from django.views.defaults import server_error, page_not_found,permission_denied

page_not_found = 'apps.freelancers.views.handler404'
server_error = 'apps.freelancers.views.handler500'



urlpatterns = [

    url(r'^site_administration/', include(admin.site.urls)),
    url(r'^$', gzip_page(views.IndexView.as_view()), name='IndexView'),
    # url(r'^register',views.RegisterView.as_view(), name='Register'),
    url(r'^accounts/', include('apps.accounts.urls')),
    url(r'^', include('apps.clients.urls')),
    url(r'^blogs/', include('apps.blogs.urls')),
    url(r'^faq/', include('apps.faq.urls')),
    url(r'^profile/', include('apps.profile.urls')),
    url(r'^', include('apps.freelancer.urls')),
    url(r'^about/$',AboutUsView.as_view(),name='about'),
    url(r'^contact/$',contact.ContactView.as_view(), name='contact_us'),
    url(r'^admin/mail/', include('apps.sendbox.urls')),
    url(r'^site_admin/', include('apps.site_admin.urls')),
    url(r'^permission_error/$', PermissionView.as_view(), name='permission_error'),
    url(r'^hire/', include('apps.hire.urls')),


    url(r'^password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': 'auth_password_reset_done',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': 'auth_password_reset_complete'},
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        name='auth_password_reset_complete'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name='auth_password_reset_done'),

        #####CKEditor #####
    url(r'^ckeditor/', include('ckeditor.urls')),


]


if 'django_comments' in settings.INSTALLED_APPS:
    # Django 1.7/1.8 situation
    COMMENT_URLS = 'django_comments.urls'


urlpatterns += patterns('',
                        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                            {'document_root': settings.STATIC_ROOT, 'show_indexes': False}),
                        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                            {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
                        url(r'^comments/', include(COMMENT_URLS)),
                        )
urlpatterns += staticfiles_urlpatterns()

apps/sendbox/models.py
from __future__ import unicode_literals

from django.utils.translation import ugettext_lazy as _
from django_countries import settings
from django.db import models
from django.core.urlresolvers import reverse

from autoslug import AutoSlugField
from ckeditor.fields import RichTextField

from apps.sendbox.settings import *

from apps.sendbox.settings import EMAIL_SEND_TYPES


class Recipients(models.Model):
    """
    Recipients model.
    """
    recipient_name = models.CharField(_('Recipient name'), max_length=255)
    to_email = models.EmailField(_('Email'), max_length=255, unique=True)

    def __str__(self):
        return self.to_email


class MailSet(models.Model):
    """
    MailSet model.
    """
    template_name = models.CharField(_('Email template name'), max_length=255)
    module_type = models.CharField(_('Email for'), max_length=255, unique=True,
                                   choices=EMAIL_SEND_TYPES,
                                   help_text="Please select the module type to configure mail")
    subject = models.CharField(_('Email subject'), max_length=255)
    from_email = models.EmailField(_('From email'), max_length=255, null=True, blank=True)
    html_content = RichTextField()
    text_content = models.TextField(null=True, blank=True)
    is_publish = models.BooleanField(default=False)
    publish_date = models.DateTimeField(auto_now=True)
    slug = AutoSlugField(populate_from='template_name')

    def __str__(self):
        return self.template_name

    class Meta:
        ordering = ['-publish_date']
        verbose_name = "Mail configuration"
        verbose_name_plural = "Mail configurations"
        default_permissions = ('add', 'change', 'delete', 'view')

    def get_absolute_url(self):
        return reverse('template_update', kwargs={'slug': self.slug})


class Attachment(models.Model):
    """
    Attachment model.
    """
    attach = models.ForeignKey(MailSet, related_name='attachments', verbose_name="Attach file")
    attach_file = models.FileField(upload_to='attachments/')

    def __str__(self):
        return self.attach.module_type


class MailSetCampaign(models.Model):
    """
    MailSetCampaign model.
    """

    mail_set = models.OneToOneField(MailSet, related_name='template')
    to_email = models.ManyToManyField(Recipients, blank=True)
    attach = models.ForeignKey(Attachment, null=True, blank=True)
    is_publish = models.BooleanField(default=False)
    publish_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.mail_set.template_name

    class Meta:
        ordering = ['-publish_date']
        verbose_name = "Mail Campaign"
        verbose_name_plural = "Mail Campaigns"
        default_permissions = ('add', 'change', 'delete', 'view')

apps/sendbox/views.py
import json
from django.http import HttpResponseRedirect, HttpResponse
from django.template.response import TemplateResponse
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from django.template import RequestContext
from django.template.loader import render_to_string

from apps.sendbox.forms import MailSetForm, MailSetCampaignForm, EmailTemplateUpdateForm, MailSetCampaignUpdateForm
from apps.sendbox.models import MailSet, MailSetCampaign
from django.contrib.auth.decorators import login_required, user_passes_test
from functools import wraps


class EmailTemplateUpdateView(ListView):

    model = MailSet
    form = EmailTemplateUpdateForm
    template_name = 'email_template_update.html'

    def get_context_data(self, **kwargs):
        context = super(EmailTemplateUpdateView, self).get_context_data(**kwargs)
        context['active_menu'] = 'email_update'
        context['active_tab'] = 'update_temp'
        try:
            mailSet = MailSet.objects.get(slug=self.kwargs['slug'])
            context['form'] = EmailTemplateUpdateForm(instance=mailSet)
            try:
                template_obj = MailSetCampaign.objects.get(mail_set=mailSet)
                context['user_form'] = MailSetCampaignForm(instance=template_obj)
            except:
                context['user_form'] = MailSetCampaignForm()
        except:
            context['form'] = EmailTemplateUpdateForm()
            context['user_form'] = MailSetCampaignForm()

        return context

    def post(self, request, *args, **kwargs):
        mailSet = MailSet.objects.get(slug=self.kwargs['slug'])
        message = None
        if request.POST.get('Form_type') == 'assign_user':
            active_tab = 'assign_user'
            try:
                mailSet = MailSet.objects.get(slug=self.kwargs['slug'])
                form = EmailTemplateUpdateForm(instance=mailSet)
                template_obj = MailSetCampaign.objects.get(mail_set=mailSet)
                user_form = MailSetCampaignUpdateForm(request.POST, instance=template_obj)
                if user_form.is_valid():
                    users_form = user_form.save(commit=False)
                    users_form.save()
                    user_form.save_m2m()
                    message = 'Update users email successfully'
                else:
                    print "user_form error", user_form.errors
            except:
                user_form = MailSetCampaignForm(request.POST)
                if user_form.is_valid():
                    user_form.save()
                    message = 'Update users email successfully'
                else:
                    print "user_form error", user_form.errors
        else:
            form = self.form(request.POST, instance=mailSet)
            active_tab = 'update_temp'
            if form.is_valid():
                new_form = form.save(mail_obj=mailSet)
                message = 'Update  template successfully'
            else:
                print form.errors
            try:
                mailSet = MailSet.objects.get(slug=new_form.slug)
                template_obj = MailSetCampaign.objects.get(mail_set=mailSet)
                user_form = MailSetCampaignForm(instance=template_obj)
            except:
                user_form = MailSetCampaignForm()
        context = {'errors': form.errors, 'form': form, 'user_form': user_form, 'active_tab': active_tab,
                   'message': message}
        return TemplateResponse(request, self.template_name, context)


class EmailTemplateListView(ListView):

    model = MailSet
    template_name = 'email_template_list.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(EmailTemplateListView, self).get_context_data(**kwargs)
        context['active_menu'] = 'email_list'
        return context


class EmailCreateView(ListView):
    template_name = "email_create.html"
    form_class = MailSetForm
    model = MailSet

    def get_context_data(self, **kwargs):
        context = super(EmailCreateView, self).get_context_data(**kwargs)
        context['active_menu'] = 'email_create'
        context['active_tab'] = 'update_temp'
        context['form'] = MailSetForm()
        context['user_form'] = MailSetCampaignForm()

        return context

    def post(self, request, *args, **kwargs):
        message = None
        if request.POST.get('Form_type') == 'assign_user':
            active_tab = 'assign_user'
            try:
                mailSet = MailSet.objects.get(id=request.POST.get('mail_set'))
                template_obj = MailSetCampaign.objects.get(mail_set=mailSet)
                user_form = MailSetCampaignUpdateForm(request.POST, instance=template_obj)
                if user_form.is_valid():
                    item_form = user_form.save(commit=False)
                    item_form.save()
                    user_form.save_m2m()
                    message = 'Success'
                else:
                    print "user_form error", user_form.errors
            except:
                user_form = MailSetCampaignForm(request.POST)
                if user_form.is_valid():
                    user_form.save()
                    message = 'data added successfully'
                else:
                    print "user_form error", user_form.errors
            try:
                mail_set_id = request.POST.get('mail_set')
                mail_obj = MailSet.objects.get(template__mail_set=mail_set_id)
                form = self.form_class(instance=mail_obj)
            except:
                form = self.form_class()
        else:
            form = self.form_class(request.POST)
            active_tab = 'update_temp'
            if form.is_valid():
                form.save()
                message = 'data added successfully'
            else:
                print form.errors
            # try:
            #     mail_set_id = form.id
            #     print "IIIII", mail_set_id
            #     mail_obj = MailSetCampaign.objects.get(id=mail_set_id)
            #     print "FFFFFFFFFFFFFFFFFFFF", mail_obj
            #     user_form = MailSetCampaignForm(instance=mail_obj)
            # except:
            #     user_form = MailSetCampaignForm()
            user_form = MailSetCampaignForm()


        context = {'active_menu': 'email_create', 'errors': form.errors, 'form': form, 'user_form': user_form,
                   'message': message, 'active_tab': active_tab}
        return TemplateResponse(request, self.template_name, context)


class StaticCampaignSetUpView(ListView):
    template_name = "set_up_static_campaign.html"
    form = MailSetCampaignForm
    model = MailSetCampaign

    def get_context_data(self, **kwargs):
        data = super(StaticCampaignSetUpView, self).get_context_data(**kwargs)
        data['active_menu'] = 'email_setup'
        data['form'] = MailSetCampaignForm()
        #print "hhhhhhhh", self.request.GET.get('mail_set')
        return data

    def post(self, request, *args, **kwargs):
        message = None
        if request.is_ajax():
            response_data = {}
            response_data['status'] = True
            try:
                mailSet = MailSet.objects.get(id=request.POST.get('mail_set'))
                template_obj = MailSetCampaign.objects.get(mail_set=mailSet)
                form = MailSetCampaignForm(instance=template_obj)
            except:
                form = MailSetCampaignForm()
                response_data['status'] = False
            print "form", form
            response_data['html_content'] = render_to_string('ajax/email_recipients.html',
                                                             {'form': form},
                                                             context_instance=RequestContext(request))
            return HttpResponse(json.dumps(response_data), content_type="application/json")

        else:
            try:
                mailSet = MailSet.objects.get(id=request.POST.get('mail_set'))
                template_obj = MailSetCampaign.objects.get(mail_set=mailSet)
                form = MailSetCampaignUpdateForm(request.POST, instance=template_obj)
                if form.is_valid():
                    item_form = form.save(commit=False)
                    item_form.save()
                    form.save_m2m()
                    message = 'Success'
                else:
                    print "user_form error", form.errors
            except:
                form = MailSetCampaignForm(request.POST)
                if form.is_valid():
                    form.save()
                    message = 'Success'
                else:
                    print "user_form error", form.errors
            context = {'active_menu': 'email_setup',  'form': form, 'errors': form.errors, 'message': message}
            return TemplateResponse(request, self.template_name, context)

apps/sendbox/templates/email_template_update.html
{% extends 'admin_base.html' %}
{% block title %}Create email{% endblock %}
{% block extra_css %}

{% endblock %}
{% block content %}
<!-- adminMenuSection ends here -->
{% if  message != None  %}
<div class="alert-success alert_modal fade in alert_box">
    <span class="close" onclick="alertClose();">X</span>
    <strong>Success! </strong>  Your data has been saved .
</div>
{% endif %}

<div class="alert-warning alert_modal fade in alert_box">
    <span class="close" onclick="alertClose();">X</span>
    <strong>Alert! </strong>  Please create a template first .
</div>
<div class="alert-warning alert_modal fade in alert_box alert_mismatch">
    <span class="close" onclick="alertClose();">X</span>
    <strong>Alert! </strong>  Mismatch in selected data with template selected .
</div>

<div class="tab_holder">
    <ul>
        <li data-post="registration" class="{% if active_tab == 'update_temp'%} active {% endif %}">Template registration</li>
        <li data-post="assign_user" class="{% if active_tab == 'assign_user'%} active {% endif %}">Assign User</li>
    </ul>
</div>
<div class="clearfix tab-list" id="registration"  {% if active_tab == 'update_temp'%} style="display: block;" {% endif %} >
    <div class="registrationMainSect">
        <p class="reg"><span><i class="fa fa-file-text-o"></i></span>Template registration</p>
        <form role="form" action="." method="post" class="registrationForm">{% csrf_token %}
            <input type="hidden" name="Form_type" value="registration">
            {{ form.media }}
            <div class="admin_email_container">
                <div class="registrationFormGroup">
                    <label for="id_template_name">Template name</label>
                    {{ form.template_name }}
                    {{ form.template_name.errors }}
                </div>
                <div class="registrationFormGroup">
                    <label for="id_module_type">Module types...</label>
                    {{ form.module_type }}
                    {{ form.module_type.errors }}
                </div>
                <div class="registrationFormGroup">
                    <label for="id_subject">Subject</label>
                    {{ form.subject }}
                    {{ form.subject.errors }}
                </div>

                <div class="registrationFormGroup">
                    <label for="id_html_content">Html content</label>
                    <div class="editor_container">
                        {{ form.html_content }}
                        {{ form.html_content.errors }}
                    </div>
                </div>
                <div class="registrationFormGroup">
                    <label for="id_text_content">Text content(Optional)</label>
                    {{ form.text_content }}
                    {{ form.text_content.errors }}
                </div>
                 <div class="registrationFormGroup">
                    <label for="id_is_publish">Is published</label>
                    {{ form.is_publish }}
                </div>

                <div class="registrationFormGroup">
                    <input type="submit" value="Save" class="submitBtn">
                </div>
            </div>

            <div class="clear"></div>
        </form>

        <div class="clear"></div>
    </div>
    <!-- registrationMainSect closes here -->
</div>
<div class="clearfix tab-list" id="assign_user" {% if active_tab == 'assign_user'%} style="display: block;" {% endif %} >
    <div class="registrationMainSect">
        <p class="reg"><span><i class="fa fa-file-text-o"></i></span>Template registration</p>
        <form role="form" action="." method="post" class="registrationForm">{% csrf_token %}
            <input type="hidden" name="Form_type" value="assign_user">
            {{ user_form.media }}
            <div class="admin_email_container">
                <input type="hidden" name="mail_set" value="">
                <div class="registrationFormGroup">
                    <label for="id_mail_set">Template name</label>
                    {{ user_form.mail_set }}
                    {{ use_form.mail_set.errors }}
                </div>
                <div class="registrationFormGroup">

                    {{ user_form.to_email }}

                </div>
                <div class="registrationFormGroup">
                    <label for="id_is_publish">Is published</label>
                    {{ user_form.is_publish }}
                    {{ user_form.is_publish.errors }}
                </div>

                <div class="registrationFormGroup">
                    <input type="submit" value="Save" class="submitBtn">
                    <!--<input type="submit" value="Reset" class="submitBtn">-->
                </div>
            </div>

            <div class="clear"></div>
        </form>


        <div class="clear"></div>
    </div>
</div>


{% endblock %}

{% block extra_js %}
<script src="/static/admins/js/dropzone.js"></script>
<script src="/static/admins/js/jquery.multi-select.js" type="text/javascript"></script>
<script src="/static/admins/js/jquery.quicksearch.js" type="text/javascript"></script>

<script type="text/javascript">

    $(function() {
        $('.tab_holder').find('li').each(function() {
            if ($(this).hasClass('active')) {
                var sectionId = $(this).attr('data-post');
                $('#' + sectionId + '').show();
            }
        });
    });
    $(document).on('click', '.tab_holder li', function() {
        var sectionId = $(this).attr('data-post');
        $('.tab_holder').find('li').each(function() {
            var sectionIdSearch = $(this).attr('data-post');
            $('#' + sectionIdSearch + '').hide();
            $(this).removeClass('active');
        });
        $(this).addClass('active');
        $('#' + sectionId + '').show();


    });

    $('#roleSelection').multiSelect({
        selectableHeader: "<div class='head3'>Available Permission</div><input type='text' class='search-input col-md-12' autocomplete='on' placeholder='search..'>",
        selectionHeader: "<div class='head3'>Chosen Permission</div>",
        selectionFooter:"<button class='custom-footer btn deselect_role' type='button'><i class='fa fa-times'></i> <span>Remove all </span></button>",
        selectableFooter:"<button class='custom-footer btn select_role' type='button'><i class='fa fa-check'></i><span>Choose all</span></button>",
        afterInit: function(ms){
        var that = this,
            $selectableSearch = that.$selectableUl.prev(),
            $selectionSearch = that.$selectionUl.prev(),
            selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
            selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

        that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
        .on('keydown', function(e){
          if (e.which === 40){
            that.$selectableUl.focus();
            return false;
          }
        });

        that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
        .on('keydown', function(e){
          if (e.which == 40){
            that.$selectionUl.focus();
            return false;
          }
        });
      },
      afterSelect: function(){
        this.qs1.cache();
        this.qs2.cache();
      },
      afterDeselect: function(){
        this.qs1.cache();
        this.qs2.cache();
      }
    });
    $(document).on("click",".custom-footer.deselect_role", function(){
        $('#roleSelection').multiSelect('deselect_all');
    });
    $(document).on("click",".custom-footer.select_role", function(){
        $('#roleSelection').multiSelect('select_all');
    });
    $(document).on("change","#id_mail_set", function(){
        var select_box = $("#id_mail_set option:selected").text();
        var temp_name = $('#id_template_name').val();
        if(temp_name.length == 0){
            $('.alert-warning').show();
            $('.alert-warning').delay(2500).fadeOut(400);
        }
        if (select_box != temp_name){
            $('.alert_mismatch').show();
            $('.alert_mismatch').delay(2500).fadeOut(400);
        }
    });

// *********************************************************



    $(document).ready(function() {

        $('.alert_modal').delay(2500).fadeOut(250);
        /*************** select box in assign user tab******************/
            var select_box = $("#id_mail_set option:selected").text();
            var select_box_val = $("#id_mail_set option:selected").val();
            var temp_name = $('#id_template_name').val();
            console.log(select_box);
            if ((select_box=='---------')&& (temp_name.length != 0)){
               $("#id_mail_set option:contains(" + temp_name +")").attr("selected", true);
            }
            $('input[name=mail_set]').val(select_box_val);
            $('#id_mail_set').prop("disabled", true);


          // instantiate the uploader
          Dropzone.options.myAwesomeDropzone = { // The camelized version of the ID of the form element
            // The configuration we've talked about above
            url: '.',
            previewsContainer: ".dropzone-previews",
            uploadMultiple: true,
            parallelUploads: 100,
            maxFiles: 100,
            addRemoveLinks: true,
            init: function() {

              this.on('success', function(file, json) {

              });

              this.on('addedfile', function(file) {
              });

              this.on('drop', function(file) {

              });
            },
            uploadprogress:function() {
                console.log(1);
                $('.dropzone-previews').find('.dz-remove').html('<i class="fa fa-trash-o"></i>');
                $('.dropzone-previews').addClass('file-dropzone-padding');
                $('.dropzone-previews .dz-message').addClass('file-dropzone-message');

            },
            queuecomplete:function() {
                $('.dropzone-previews').find('.dz-remove').html('<i class="fa fa-trash-o"></i>');
            }


          }



        $('#dropdownProfile').click(function() {
            $('#dropdown').toggle();
        });

    });

    /*************Jquery for Assign user tab********************/

    $('#id_to_email').multiSelect({
        selectableHeader: "<div class='head3'>Available Recipients</div><input type='text' class='search-input col-md-12' autocomplete='on' placeholder='search..'>",
        selectionHeader: "<div class='head3'>Chosen Recipients</div>",
        selectionFooter:"<button class='custom-footer btn deselect_role' type='button'><i class='fa fa-times'></i> <span>Remove all </span></button>",
        selectableFooter:"<button class='custom-footer btn select_role' type='button'><i class='fa fa-check'></i><span>Choose all</span></button>",
        afterInit: function(ms){
        var that = this,
            $selectableSearch = that.$selectableUl.prev(),
            $selectionSearch = that.$selectionUl.prev(),
            selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
            selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

        that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
        .on('keydown', function(e){
          if (e.which === 40){
            that.$selectableUl.focus();
            return false;
          }
        });

        that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
        .on('keydown', function(e){
          if (e.which == 40){
            that.$selectionUl.focus();
            return false;
          }
        });
      },
      afterSelect: function(){
        this.qs1.cache();
        this.qs2.cache();
      },
      afterDeselect: function(){
        this.qs1.cache();
        this.qs2.cache();
      }
    });
    $(document).on("click",".custom-footer.deselect_role", function(){
        $('#id_to_email').multiSelect('deselect_all');
    });
    $(document).on("click",".custom-footer.select_role", function(){
        $('#id_to_email').multiSelect('select_all');
    });
</script>
{% endblock %}